#pragma once
#include "../core/NeuralFieldSystem.hpp"

// OPTIMIZED VERSION - Generated by EvolutionModule
// More efficient damping and limits
class DynamicsOptimized {
public:
    void applyOptimizedDynamics(NeuralFieldSystem& system) {
        auto& phi = system.getPhi();
        auto& pi = system.getPi();
        
        // Optimized damping
        for (int i = 0; i < system.N; i++) {
            pi[i] *= 0.995;
        }
        
        // Optimized limits
        for (int i = 0; i < system.N; i++) {
            if (phi[i] > 1.5) phi[i] = 1.5;
            if (phi[i] < -1.5) phi[i] = -1.5;
        }
    }
};
