#pragma once
#include "../core/NeuralFieldSystem.hpp"

// OPTIMIZED VERSION - Generated by EvolutionModule
// More efficient Hebbian learning
class LearningOptimized {
public:
    void applyOptimizedLearning(NeuralFieldSystem& system) {
        auto& W = system.getWeights();
        const auto& phi = system.getPhi();
        
        // Sparse weight updates for efficiency
        for (int i = 0; i < system.N; i += 2) {
            for (int j = i + 1; j < system.N; j += 2) {
                double update = 0.0003 * phi[i] * phi[j];
                W[i][j] = W[i][j] * 0.998 + update;
                W[j][i] = W[i][j];
            }
        }
    }
};
